# Generated by Django 4.0.2 on 2022-02-27 05:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "questionn_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                ("answer_choices", models.CharField(max_length=1000)),
                (
                    "answer_template",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("radio", "Radio"),
                            ("check", "CheckBox"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "English")], default="EN", max_length=2
                    ),
                ),
                ("active", models.BooleanField()),
                (
                    "additional_info",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField()),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions_created",
                        to="users.campaignuser",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "response_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=1000)),
                ("location", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField()),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="campaigns.question",
                    ),
                ),
                (
                    "site_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="users.agencysite",
                    ),
                ),
            ],
            options={
                "db_table": "responses",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "campaign_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(null=True)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("agent", "Agent"),
                            ("staff", "Staff"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField()),
                ("qr_code_path", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField()),
                (
                    "create_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns_created",
                        to="users.campaignuser",
                    ),
                ),
                ("questions", models.ManyToManyField(to="campaigns.Question")),
                ("sites", models.ManyToManyField(to="users.AgencySite")),
            ],
            options={
                "db_table": "campaigns",
            },
        ),
    ]
