# Generated by Django 4.0.2 on 2022-03-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_deleted_at_alter_qrcode_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
    ]
