# Generated by Django 4.0.2 on 2022-03-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_remove_campaign_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="slug",
            field=models.CharField(max_length=200),
        ),
    ]
