# Generated by Django 4.0.3 on 2022-03-22 14:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_alter_qrcode_qr_code_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="id",
        ),
        migrations.AddField(
            model_name="qrcode",
            name="qr_code_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
