# Generated by Django 4.0.3 on 2022-03-25 02:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0008_remove_question_create_by_campaign_campaign_owner_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "answer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_value", models.CharField(max_length=1000)),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "English")], default="EN", max_length=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "answer_choices",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="answer_choices",
        ),
        migrations.AddField(
            model_name="question",
            name="answer_choices",
            field=models.ManyToManyField(to="campaigns.answerchoice"),
        ),
    ]
