# Generated by Django 4.0.3 on 2022-03-28 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_answerchoice_remove_question_answer_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='campaigns.campaign'),
        ),
    ]
