# Generated by Django 4.0.3 on 2022-03-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_response_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_choices',
            field=models.ManyToManyField(blank=True, to='campaigns.answerchoice'),
        ),
    ]
