# Generated by Django 4.0.3 on 2022-03-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_remove_campaign_questions_campaignquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='questions',
            field=models.ManyToManyField(through='campaigns.CampaignQuestion', to='campaigns.question'),
        ),
    ]
