# Generated by Django 4.0.3 on 2022-03-30 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_campaign_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignquestion',
            name='id',
        ),
        migrations.AddField(
            model_name='campaignquestion',
            name='campaign_question_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
