# Generated by Django 4.0.3 on 2022-03-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_remove_campaignquestion_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignquestion',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='campaignquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Value needs to be > 0'),
        ),
    ]
