# Generated by Django 4.0.2 on 2022-03-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_agencysite_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencysite",
            name="name",
            field=models.CharField(default="fake", max_length=200),
            preserve_default=False,
        ),
    ]
