# Generated by Django 4.0.3 on 2022-03-22 14:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_agencysite_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencysite",
            name="site_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
